### ISSUE TITLE
Hotspot which isn't revealed with the space bar

### ISSUE THREAD

**Issue by MikaelNyqvist** [deep-entertainment/issues#11]
**Is your feature request related to a problem? Please describe.**
It could sometimes be advisable to use hotspots that aren't revealed when space is pressed (i.e. in some minigames I'm planning for my next game). Or for that matter, if one were to create a scene with hidden object elements.

**Describe the solution you'd like**
While several solutions are possible, I think that a new hotspot class, identical to the regular hotspot, except that it's not revealed by the space bar, would be ideal.

**Comment by dploeger** [comment]
Fixed in https://github.com/deep-entertainment/egoventure-example-game/pull/14
