### ISSUE TITLE
[EGOVENTURE] check_cursor() resets cursor while having an inventory item selected

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/issues#16]
**Describe the bug**
I'm currently working on a scenery where a selected inventory item is applied multiple times in a row in different scenes. Depending on the mouse location the cursor is being reset although the inventory item is still selected.
Example:
* on Scene 1 I pick up the inventory item.
* I apply it to a trigger hotspot area, do some action and then change to Scene 2
* check_cursor() is being called by the EgoVenture change_scene() function.
* If the cursor is located within a trigger hotspot area of Scene 2, the cursor is changed back to the USE cursor, although the Inventory Item is still selected.

**Suggested fix**
Only apply check cursor in case no Inventory Item is selected:
```
func check_cursor(offset: Vector2 = Vector2(0,0)):
	if not is_touch and not Speedy.hidden and Inventory.selected_item == null:
```

**Comment by dploeger** [comment]
Already fixed in deep-entertainment/egoventure-example-game@5cb25f0fe4f8754ab662a1bcffb8dad51fb2fe1d
