### ISSUE TITLE
Menu music restarting

### ISSUE THREAD

**Issue by MikaelNyqvist** [deep-entertainment/issues#2]
Explore the possibility to not make the menu music restart (and just continue playing instead) if the same music is playing while the menu is brought up.

**Comment by dploeger** [comment]
Currently, the MainMenu is using its own MusicPlayer instead of Boombox to be able to pause and resume its own music through the game. Working around that for such a very sporadic use would be too hacky in my eyes. As discussed on Discord, I'm closing this issue for the time being.
