### ISSUE TITLE
EgoVenture: Menu sound FX.

### ISSUE THREAD

**Issue by ReichNick** [deep-entertainment/issues#26]
In Carol Reed series Main menu buttons have fx sounds. One when mouse hover button. Second when mouse click button. Please, add this option in res://configuration.tres under Menu block in inspector.

**Comment by dploeger** [comment]
Fixed in branch [issue-26](https://github.com/deep-entertainment/egoventure-example-game/tree/issue-26).

@ReichNick @MikaelNyqvist could you please try it out if it works for you?

**Comment by ReichNick** [comment]
Tested. All good.
