### ISSUE TITLE
Control placement of inventory items

### ISSUE THREAD

**Issue by MikaelNyqvist** [deep-entertainment/issues#28]
If an inventory item will be viewed in close-up constantly, and serve useful informational purposes, like an extra journal or an infosheet, it would be practical to place it to the left in the inventory. As the "first" object, that is. As it is now, the placement of the inventory items can not be controlled.

**Comment by dploeger** [comment]
Added the feature in branch issue-28. Please [download it](https://github.com/deep-entertainment/egoventure-example-game/archive/refs/heads/issue-28.zip) and try it out.

**Comment by dploeger** [comment]
Included in 2.1.0
