### ISSUE TITLE
Option for non-grabbable items.

### ISSUE THREAD

**Issue by MikaelNyqvist** [deep-entertainment/issues#31]
An option for toggling inventory items as "non grabbable" (i.e. not being possible to drag into the gaming area, but stay as stationary items in the inventory) would be useful. These object should also show the custom detail view when left clicked.

**Comment by dploeger** [comment]
Implemented in branch issue-31. Please test: https://github.com/deep-entertainment/egoventure-example-game/archive/refs/heads/issue-31.zip

**Comment by dploeger** [comment]
Merged in Develop.

**Comment by dploeger** [comment]
Fixed in 2.2.0
