### ISSUE TITLE
Add configuration for vertical separation of menu items on main menu

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/issues#33]
Project:

- [X] Egoventure

**Is your feature request related to a problem? Please describe.**
The menu items in the main menu have a fixed separation of 30 (pixel) in the VBoxContainer settings in main_menu.tscn. This is causing issues when using a large menu font (or having extra space added to the font).

**Describe the solution you'd like**
Therefore I suggest to add a new configuration parameter in configuration.tres which controls the vertical distance between the menu items.

**Describe alternatives you've considered**
An alternative would be to use negative space settings for the menu font, but this has unwanted side effects to other menu screens.

I'll add a pull request introducing a new configuration parameter menu_item_separation for the main menu.

**Comment by dploeger** [comment]
Merged to Develop

**Comment by dploeger** [comment]
Fixed in 2.2.0
