### ISSUE TITLE
[EGOVENTURE] Save Game screenshots are in 16:9 also if project uses different Width/Height ratio

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/issues#35]
**Describe the bug**
In MainMenu function _on_slot_selected() a screenshot is generated when saving a game.
The screenshot is being resized to 16:9 format by:
`screenshot.resize(464, 261, Image.INTERPOLATE_NEAREST)`

When creating a game in a different aspect ratio the pictures shown in the save slots are being distorted. 

**Proposal**
Use the ProjectSettings 'display/window/size/width' and 'height' for example divided by 5 to determine the target size of the save game screenshot.

**Versions**
* Egoventure: all

**Comment by dploeger** [comment]
Oh right. I've added a fix in the branch issue-35. Could you please check it out and the [linked PR](https://github.com/deep-entertainment/egoventure-example-game/pull/39)?
