### ISSUE TITLE
Option to change the mouse cursor for the volume slider.

### ISSUE THREAD

**Issue by Allegrio** [deep-entertainment/issues#44]
I would propose adding to possibility to customize the mouse cursor for the "grabber" icon for the volume slider in the options menu.

**Comment by dploeger** [comment]
As discussed on Discord, it should rather always be the Hand cursor. Currently it seems to be the pointer cursor.

**Comment by Allegrio** [comment]
I pasted in the changed line in check_cursor.gd (that should do it, right?), and it works like a charm! Exactly as expected!

**Comment by dploeger** [comment]
Fixed in deep-entertainment/egoventure-example-game@8960b028a228c2e017a53e6fc32cf0dba190479c
