### ISSUE TITLE
[EGOVENTURE] Menu items: display issues

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/issues#46]
@MikaelNyqvist encountered some menu item display issues:

Issues when using a different font definition in the theme for menu_button and menu_button_hover:
- issue 1: When leaving the load/save menu with Cancel or leaving the options menu with Return, and then going back to the load/save or options menu, the Cancel / Return button is still being displayed with menu_button_hover font.
Reason is that the mouse_exited event is not being raised by Godot when the button is hidden.
-> Solution: raise the mouse exited event when hiding the load/save menu or the options menu.
- issue 2: When the mouse is hovered over a disabled menu item, it is also getting updated with the menu_button_hover font.
(Also a sound effect is being played for disabled buttons when it is defined.)
-> Solution: Add a check that the font is only getting updated for menu items that are not disabled.
- issue 3: When pushing the mouse button on a menu item and keeping it pressed and then moving the mouse outside of the button area:
   - the font color switches from font_color_pressed to font_color
   - but the font does not switch from menu_button_hover to menu_button
-> Solution: set parameter 'keep_pressed_outside' for menu item buttons

Issue with menu item focus color
- issue 4: When setting font_color_focus in the theme the focus feature is enabled for the menu item buttons. When the main menu is displayed first, no menu item is focused and it is not possible to switch between the menu items with TAB. Once the first menu item got selected, the focus color is set to the button and it is possible to use TAB to switch between the menu items. It is also possible to put focus on the disabled buttons.
-> Solution Proposal: Disable the focus feature for menu items and only allow selection of menu items with the mouse.

I'll add a pull request containing enhancements to the menu and the menu button to address these issues.

**Comment by MikaelNyqvist** [comment]
Excellent!
