### ISSUE TITLE
[EGOVENTURE] MainMenu QuitConfirm propagates input event when closing the dialog

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/issues#5]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
The MainMenu node QuitConfirm propagate an input event when closing the dialog. This is an issue when clicking outside of the confirmation dialog as the input is the propagated to the MainMenu.
Another example is the OverwriteConfirm in case you want to close the confirmation by clicking in an area of an empty save slot, the game will close the dialog and saves the game in this slot.

**To Reproduce**
1. Select "Quit" in the main menu to enable the QuitConfirm dialog
2. Click outside of the confirmation window on 'Settings'.
3. The confirmation dialog will close and you jump directly into 'Settings'

**Expected behavior**
A click outside of the confirmation should simply close the dialog w/o event propagation.

**Recommended fix**
Set property 'input_pass_on_modal_close_click' on all confirmation dialogs to 'false'.

**Comment by dploeger** [comment]
Should be fixed in the re-release of the current version. Sorry about the mixup
