### ISSUE TITLE
[EGOVENTURE] "OK" button in menu confirm dialogs is highlighted by default

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/issues#6]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
When a confirm dialog is opened in the main menu, the OK button is highlighted as default as if it would have the mouse focus.
When moving the mouse on 'Cancel' then both options are highlighted.
When moving the mouse over 'OK' then the highlight gets removed.

**Proposed fix**
Add following code to main_menu.gd -> configure function:
`# Disable focus of OK buttons on confirm dialogs`
`$Menu/QuitConfirm.get_ok().enabled_focus_mode = 0`
`$Menu/OverwriteConfirm.get_ok().enabled_focus_mode = 0`
`$Menu/RestartConfirm.get_ok().enabled_focus_mode = 0`

Then only a focus via mouse is allowed and you can't select the focus with the keyboard.

**Comment by dploeger** [comment]
This is already fixed in the develop branch of the example game. We'll update the versions in the coming days.

**Comment by dploeger** [comment]
Should be fixed in the re-release of the current version. Sorry, was a little mixed up.
