### ISSUE TITLE
Godot 3.4: Custom resource 'InventoryItem' is not found in TriggerHotspot node

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/issues#8]
**Describe the bug**
I'd like to inform you about a potential incompatibility in Godot 3.4 that doesn't allow to add an InventoryItem into the valid inventory items array of a TriggerHotspot.
But maybe it's also a bug that has been introduced with Godot 3.4...

**To Reproduce**
Steps to reproduce the behavior using the example game:
0. Use Godot 3.4 [It's working fine until Godot 3.3.4]
1. Go to 'scenes/man/man06c_cl.tscn'
2. Select the TriggerHotspot node in the scene tree
2. Click on 'Valid Inventory Items' in Inspector
3. --> The Output shows error message: Cannot get class 'InventoryItem'.
4. Increase the size of the Array to 2
5. Load resource 'inventory/file.tres' into the Array.
6. --> A Warning message appears: 'The selected resource (Resource) does not match any type expected for this property (InventoryItem).' and the InventoryItem does not get added,

**Versions**
* Egoventure (if applicable): 
* Parrot (if applicable): 
* Speedy Gonzales (if applicable): 
* Godot: 3.4

**Comment by dploeger** [comment]
Yes. We're aware of that and recently discussed that. We will postpone this to after we released version 1.0.0 though.
